config/routes.rb
ShotVisualizerApi::Application.routes.draw do

  get 'shotcharts', :to => 'shot_charts#show', as: 'shotcharts'

  resources :teams, only: :index
  resources :rosters, only: :show
  resources :players, only: :show

  namespace :api do
    namespace :v1 do
      resources :plays, only: :index, as: 'player_shots'
      resources :teams, only: :index
    end
  end

  root :to => 'static_pages#index'

end

app/models/play.rb
class Play

  include Mongoid::Document
  field :period, type: String
  field :seconds,  type: Integer
  field :team,  type: String
  field :etype, type: String
  field :coordinates, type: Hash
  field :points, type: Integer
  field :result, type: String
  field :shot_type, type: String
  field :season, type: String
  field :teams, type: Hash

  belongs_to :game

  def self.find_shots(data)
    results = shots_by_player(data)
    results.first[:error].present? ? results : format_response(results, data)
  end

  def self.shots_by_player(data)
    shots = query_for_player_shots(data)
    results = shots.to_ary
    results.empty? ? results << {error: "no results found"} : results
  end

  def self.query_for_player_shots(data)
    Play.and({"eplayer.name"=>data[:player]},
            {:etype.ne => "free throw"},
            {:season => data[:season]})
            .or({:result => "made"}, {:result => "missed"})
  end

  def self.format_response(results, data)
    ResponseFormatter.format_plays(results, data)
  end

end

app/models/player.rb
class Player

  include Mongoid::Document
  field :name, type: String

end

app/models/roster.rb
class Roster
  include Mongoid::Document

  field :team, type: String
  field :season, type: String
  field :players, type: Array

  belongs_to :team

  def self.find_roster(data)

    season = (data[:season].nil? ? "2008-2009" : data[:season])

    Roster.and(team_id: data[:id], season: season).first
  end

end

app/models/team.rb
class Team

  include Mongoid::Document
  field :abbr, type: String
  field :name, type: String
  field :logo_url, type: String
  field :active, type: Boolean

  def self.fetch_all(season = "2008-2009")
    teams = Team.where(:active.ne => false).to_ary
    team_rosters = []

    teams.each do |team|
      obj = {}
      obj[:team] = team
      roster = Roster.where(team_id: team.id, season: season).first.players
      obj[:roster] = roster
      team_rosters << obj
    end

    team_rosters
    format_response(team_rosters)
  end


  def self.format_response(data)
    teams = []

    data.each do |team|
      obj = {}
      obj["abbr"] = team[:team].abbr
      obj["name"] = team[:team].name
      obj["logo"] = team[:team].logo_url
      obj["roster"] = parse_roster(team[:roster])
      teams << obj
    end
    teams
  end

  def self.parse_roster(roster)
    roster.map {|player| player["name"] }
  end

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  respond_to :json

end

app/controllers/api/v1/plays_controller.rb
class Api::V1::PlaysController < Api::V1::BaseController

  def index
    @shots = Play.find_shots(params)
    respond_with @shots
  end

end

app/controllers/api/v1/teams_controller.rb
class Api::V1::TeamsController < Api::V1::BaseController
  def index
    @teams = Team.fetch_all
    respond_with @teams
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def show
    @player = Player.find_player_shots(params)
  end
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController

  def show
    @roster = Roster.find_roster(params)
  end

end

app/controllers/shot_charts_controller.rb
class ShotChartsController < ApplicationController
  layout "charts"

  def show
    shot_data = Play.find_shots(params)

    @player = shot_data[:player]
    gon.shots = shot_data[:shots]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'home'

  def index

  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all.to_ary
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{:xhmns => "http://www.w3.org/1999/xhtml", :lang => "en", "xml:lang" => "en"}
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title ShotVisualizer - Shot Location Analytics for the NBA

    %link{:href=>'http://fonts.googleapis.com/css?family=Audiowide', :rel=>'stylesheet', :type=>'text/css'}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = include_gon


  %body
    = render :partial => "shared/navbar"

    .container
      = yield

      .row-fluid.footer
        .span4
          %h3 Information
          %ul
            %li
              %a{:href => "#"} Link
            %li
              %a{:href => "#"} Link
            %li
              %a{:href => "#"} Link
            %li
              %a{:href => "#"} Link

app/views/layouts/charts.html.haml
!!!
%html{:xhmns => "http://www.w3.org/1999/xhtml", :lang => "en", "xml:lang" => "en"}
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title ShotVisualizer - Shot Location Analytics for the NBA
    %link{:href=>'http://fonts.googleapis.com/css?family=Audiowide', :rel=>'stylesheet', :type=>'text/css'}

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = include_gon


  %body
    = render :partial => "shared/navbar"

    .container
      = yield

    .container
      .row
        = render :partial => "shared/footer"

app/views/layouts/home.html.haml
!!!
%html{:xhmns => "http://www.w3.org/1999/xhtml", :lang => "en", "xml:lang" => "en"}
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title ShotVisualizer - Shot Location Analytics for the NBA
    %link{:href=>'http://fonts.googleapis.com/css?family=Audiowide', :rel=>'stylesheet', :type=>'text/css'}

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
  %body.home-page
    = render :partial => "shared/navbar"

    = yield

    .container
      .row
        = render :partial => "shared/footer"

app/views/rosters/show.html.haml
%h1=@roster.team.abbr

%h3 
  Roster for #{@roster.season}

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Player Name
  %tbody
    - @roster.players.each do |player|
      %tr
        %td
          =link_to player["name"].titleize, shotcharts_path(id: player["player_id"], player: player["name"], season: @roster.season)

app/views/shared/_footer.html.haml
.span6
  %ul.footer
    %li
      Made with Fire and Brimstone from 
      %a{:href => "https://github.com/kareemgrant"} yours truly

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-toggle" => 'collapse', "data-target" => '.nav-collapse'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "ShotVisualizer", root_path, {:class => "brand", :id => "logo"} 
      .nav-collapse
        %ul.nav
          %li
            =link_to "View Teams", teams_path
          %li
            %a{:href => '#contact'} Contact

app/views/shot_charts/show.html.haml
%h3 
  = @player[:name].titleize
%h4
  Season: #{@player[:season]}
  %br
  %br

%p
  = link_to 'Back to Team Roster', :back
.row
  .span7
    %h4 
      Shot Chart

    .filter
      %b Filter by: 
      = link_to "1st Quarter", "#", id: "filter_period_1", class: "filter_period"
      = link_to "2nd Quarter", "#", id: "filter_period_2", class: "filter_period"
      = link_to "3rd Quarter", "#", id: "filter_period_3", class: "filter_period"
      = link_to "4th Quarter", "#", id: "filter_period_4", class: "filter_period"
      = link_to "All Quarters", "#", id: "filter_period_all", class: "filter_period"

    #chart

  .span5
    %h4 Shot Distribution

    #donut-chart


  :javascript
    var all_shot_data = gon.shots


    courtobj = new courtviz();
    /* Draw court and all shot circles */
    court = courtobj.drawCourt('court1', '');

    var svg = d3.select("svg")

    var xPos = d3.scale.linear()
                 .domain([0, 50])
                 .range([500, 0])

    var jitter = d3.scale.linear()
                 .domain([0, 1])
                 .range([-5, 5])

    var color = d3.scale.ordinal()
                 .domain(["missed", "made"])
                 .range(["red", "green"])

    var pie_color = d3.scale.category20c();

    function render(shot_data){

      var shots = svg.selectAll("circle.shot")
        .data(shot_data, function(d) { return d.shot_id });

      shots.enter()
        .append("circle")
        .attr("class", "shot")
        .attr("cx", function(d){return xPos(d.coordinates.x) + jitter(Math.random()) })
        .attr("cy", function(d){return d.coordinates.y * 10 + jitter(Math.random());})
        .attr("r", 10)
        .attr("fill", function(d) { return color(d.result) })
        .transition().duration(1000).attr("r", 4);

      shots.exit().transition().duration(200)
        .attr("r", 0).remove();
    };

    //d3.json("....", render);

    render(all_shot_data)

    $(".filter_period").click( function(e){
      e.preventDefault();

      var qtr = $(this).attr("id").split("_").pop();
      console.log("filtering qtr data" + qtr);

      qtrData = $.map(all_shot_data, function(el) {

        if ((qtr== "all") || (el.period === qtr)) {
          return el;
        }
      });

      render(qtrData);

    })


    var summary = {};

    for(var i = 0; i < all_shot_data.length; i++){ 
      var shot = all_shot_data[i]; 

      if (shot.result == "made") {
        v = summary[shot.shot_type] || 0;
        summary[shot.shot_type] = v + 1;
      }
    }
    summary = $.map(summary, function(count, type) { return { count: count, type: type } })
    .sort(function(a, b){
      if (b.count > a.count){
        return 1;
      }
      else if (b.count < a.count){
        return -1;
      }else{
        return 0;
      }
    });

    summary = [summary[0], summary[1], summary[2], summary[3], summary[4]]

    var width = 380,
        height = 350,
        radius = Math.min(width, height) / 2;

    var arc = d3.svg.arc()
    .outerRadius(radius - 10)
    .innerRadius(radius - 70);

    var pie = d3.layout.pie()
    .sort(null)
    .value(function(d) { return d.count; });

    var psvg = d3.select("#donut-chart").append("svg")
    .attr("width", width)
    .attr("height", height)
    .append("g")
    .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");

    var g = psvg.selectAll(".arc")
      .data(pie(summary))
      .enter().append("g")
      .attr("class", "arc");

    g.append("path")
      .attr("d", arc)
      .style("fill", function(d, i) { return pie_color(i); });

    g.append("text")
      .attr("transform", function(d) { return "translate(" + arc.centroid(d) + ")"; })
      .attr("dy", ".35em")
      .style("text-anchor", "middle")
      .text(function(d) { console.log(d); return d.data.type; });

app/views/static_pages/index.html.haml
#banner
  .container
    .row
      .span6.offset6
        .intro
          %h3.logo ShotVisualizer
          .tagline
            %p A New Era of Basketball Analytics

.container

  %br
  %br
  .row
  %ul.logowall
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/220/thumbs/5mdhgjh3aa92kih09pgi.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/213/thumbs/slhg02hbef3j1ov4lsnwyol5o.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/3786/thumbs/hsuff5m3dgiv20kovde422r1f.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/258/thumbs/tmjfk4voqo1v34rm65982p2hu.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/221/thumbs/hj3gmh82w9hffmeh3fjm5h874.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/222/thumbs/e4701g88mmn7ehz2baynbs6e0.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/228/thumbs/ifk08eam05rwxr3yhol3whdcm.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/229/thumbs/xeti0fjbyzmcffue57vz5o1gl.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/223/thumbs/3079.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/235/thumbs/qhhir6fj8zp30f33s7sfb4yw0.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/230/thumbs/8xe4813lzybfhfl14axgzzqeq.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/224/thumbs/3083.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/236/thumbs/bvv028jd1hhr8ee8ii7a0fg4i.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/237/thumbs/uig7aiht8jnpl1szbi57zzlsh.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/231/thumbs/793.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/214/thumbs/burm5gh2wvjti3xhei5h16k8e.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/225/thumbs/0295onf2c4xsbfsxye6i.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/232/thumbs/zq8qkfni1g087f4245egc32po.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/4962/thumbs/496226812014.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/216/thumbs/2nn48xofg0hms8k326cqdmuis.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/2687/thumbs/khmovcnezy06c3nm05ccn0oj2.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/217/thumbs/wd9ic7qafgfb0yxs7tem7n5g4.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/218/thumbs/qlpk0etqwelv8artgc7tvqefu.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/238/thumbs/g9agfgof0kzui4u445wrsj3e5.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/239/thumbs/bahmh46cyy6eod2jez4g21buk.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/240/thumbs/832.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/233/thumbs/827.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/227/thumbs/yfypcwqog6qx8658sn5w65huh.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/234/thumbs/m2leygieeoy40t46n1qqv0550.gif'
    %li
      = image_tag 'http://content.sportslogos.net/logos/6/219/thumbs/b3619brnphtx65s2th4p9eggf.gif'



      -# ATL http://content.sportslogos.net/logos/6/220/thumbs/5mdhgjh3aa92kih09pgi.gif
      -# BOS http://content.sportslogos.net/logos/6/213/thumbs/slhg02hbef3j1ov4lsnwyol5o.gif
      -# BKL http://content.sportslogos.net/logos/6/3786/thumbs/hsuff5m3dgiv20kovde422r1f.gif
      -# CHA http://content.sportslogos.net/logos/6/258/thumbs/tmjfk4voqo1v34rm65982p2hu.gif
      -# CHI http://content.sportslogos.net/logos/6/221/thumbs/hj3gmh82w9hffmeh3fjm5h874.gif
      -# CLE http://content.sportslogos.net/logos/6/222/thumbs/e4701g88mmn7ehz2baynbs6e0.gif
      -# DAL http://content.sportslogos.net/logos/6/228/thumbs/ifk08eam05rwxr3yhol3whdcm.gif
      -# DEN http://content.sportslogos.net/logos/6/229/thumbs/xeti0fjbyzmcffue57vz5o1gl.gif
      -# DET http://content.sportslogos.net/logos/6/223/thumbs/3079.gif
      -# GSW http://content.sportslogos.net/logos/6/235/thumbs/qhhir6fj8zp30f33s7sfb4yw0.gif
      -# HOU http://content.sportslogos.net/logos/6/230/thumbs/8xe4813lzybfhfl14axgzzqeq.gif
      -# IND http://content.sportslogos.net/logos/6/224/thumbs/3083.gif
      -# LAC http://content.sportslogos.net/logos/6/236/thumbs/bvv028jd1hhr8ee8ii7a0fg4i.gif
      -# LAL http://content.sportslogos.net/logos/6/237/thumbs/uig7aiht8jnpl1szbi57zzlsh.gif
      -# MEM http://content.sportslogos.net/logos/6/231/thumbs/793.gif
      -# MIA http://content.sportslogos.net/logos/6/214/thumbs/burm5gh2wvjti3xhei5h16k8e.gif
      -# MLW http://content.sportslogos.net/logos/6/225/thumbs/0295onf2c4xsbfsxye6i.gif
      -# MIN http://content.sportslogos.net/logos/6/232/thumbs/zq8qkfni1g087f4245egc32po.gif
      -# NOP http://content.sportslogos.net/logos/6/4962/thumbs/496226812014.gif
      -# NYK http://content.sportslogos.net/logos/6/216/thumbs/2nn48xofg0hms8k326cqdmuis.gif
      -# OKC http://content.sportslogos.net/logos/6/2687/thumbs/khmovcnezy06c3nm05ccn0oj2.gif
      -# ORL http://content.sportslogos.net/logos/6/217/thumbs/wd9ic7qafgfb0yxs7tem7n5g4.gif
      -# PHL http://content.sportslogos.net/logos/6/218/thumbs/qlpk0etqwelv8artgc7tvqefu.gif
      -# PHX http://content.sportslogos.net/logos/6/238/thumbs/g9agfgof0kzui4u445wrsj3e5.gif
      -# POR http://content.sportslogos.net/logos/6/239/thumbs/bahmh46cyy6eod2jez4g21buk.gif
      -# SAC http://content.sportslogos.net/logos/6/240/thumbs/832.gif
      -# SAS http://content.sportslogos.net/logos/6/233/thumbs/827.gif
      -# TOR http://content.sportslogos.net/logos/6/227/thumbs/yfypcwqog6qx8658sn5w65huh.gif
      -# UTA http://content.sportslogos.net/logos/6/234/thumbs/m2leygieeoy40t46n1qqv0550.gif
      -# WAS http://content.sportslogos.net/logos/6/219/thumbs/b3619brnphtx65s2th4p9eggf.gif